// autogit — auto stage→commit→push after every agent turn
// Generated by `autogit setup`. Delete this file to unwire Pi.
import { spawn } from "node:child_process";

// npm installs autogit as .ps1/.cmd shims — Windows spawn needs cmd /c to run those
const run = (args: string[], cwd: string, opts: object = {}) =>
  spawn("cmd", ["/c", "autogit", ...args], { cwd, windowsHide: true, ...opts });

export default function (pi) {
  const id = "pi-" + process.pid;
  let missing = false; // autogit absent — stay silent after the first notice

  const busy = (ctx) => {
    if (missing) return;
    run(["busy", "--id", id], ctx.cwd, { stdio: "ignore" }).on("error", () => {});
  };
  pi.on("agent_start", (_event, ctx) => busy(ctx));
  pi.on("tool_execution_end", (_event, ctx) => busy(ctx)); // refresh during long turns

  pi.on("agent_end", (_event, ctx) => {
    if (missing) return;
    const p = run(["ship", "--id", id], ctx.cwd, { stdio: ["ignore", "ignore", "pipe"] });
    let err = "";
    p.stderr.on("data", (d) => { err += d; });
    const notify = (msg) => { try { ctx.ui.notify(msg, "error"); } catch {} }; // ctx may be stale after session end
    p.on("close", (code) => {
      // cmd /c exits 1 with "not recognized" when autogit is not installed — notify once, then mute
      if (code !== 0) {
        if (/not recognized|is not recognized/i.test(err)) {
          if (!missing) notify("autogit not installed — auto-commit off for this session");
          missing = true;
        } else {
          notify("autogit: " + (err.trim() || "ship failed"));
        }
      }
    });
    p.on("error", () => { missing = true; });
  });
}
