// autogit — auto stage→commit→push after every agent turn
// Generated by `autogit setup`. Delete this file to unwire Pi.
import { spawn } from "node:child_process";

export default function (pi) {
  const id = "pi-" + process.pid;
  const busy = (ctx) => {
    spawn("autogit", ["busy", "--id", id], { cwd: ctx.cwd, stdio: "ignore" }).on("error", () => {});
  };
  pi.on("agent_start", (_event, ctx) => busy(ctx));
  pi.on("tool_execution_end", (_event, ctx) => busy(ctx)); // refresh during long turns

  pi.on("agent_end", (_event, ctx) => {
    const p = spawn("autogit", ["ship", "--id", id], { cwd: ctx.cwd, stdio: ["ignore", "ignore", "pipe"] });
    let err = "";
    p.stderr.on("data", (d) => { err += d; });
    const notify = (msg) => { try { ctx.ui.notify(msg, "error"); } catch {} }; // ctx may be stale after session end
    p.on("close", (code) => {
      if (code !== 0) notify("autogit: " + (err.trim() || "ship failed"));
    });
    p.on("error", () => notify("autogit: not found on PATH"));
  });
}
