// autogit — auto stage→commit→push after every agent turn
// Generated by `autogit setup`. Delete this file to unwire Pi.
import { execFile, spawn } from "node:child_process";
import { getMode } from "../neura/mode-state.ts";
import { inspectAction } from "../neura/action-policy.ts";
import { recordDecision } from "../neura/approval-store.ts";
import { addCockpitNotice, patchCockpit, removeCockpitNotice } from "../neura/cockpit-state.ts";

// npm installs autogit as .ps1/.cmd shims — Windows spawn needs cmd /c to run those
const run = (args: string[], cwd: string, opts: object = {}) =>
  spawn("cmd", ["/c", "autogit", ...args], { cwd, windowsHide: true, ...opts });

const hasChanges = (cwd: string): Promise<boolean> => new Promise((resolve) => {
  execFile("git", ["status", "--porcelain"], { cwd, windowsHide: true }, (error, stdout) =>
    resolve(!error && !!stdout.trim()),
  );
});

export default function (pi) {
  if (!process.env.NEURA) return;

  const id = "pi-" + process.pid;
  let missing = false; // autogit absent — stay silent after the first notice

  const busy = (ctx) => {
    if (missing || getMode() !== "yolo") return;
    run(["busy", "--id", id], ctx.cwd, { stdio: "ignore" }).on("error", () => {});
  };
  pi.on("agent_start", (_event, ctx) => busy(ctx));
  pi.on("tool_execution_end", (_event, ctx) => busy(ctx)); // refresh during long turns

  pi.on("agent_end", async (_event, ctx) => {
    if (missing) return;
    const mode = getMode();
    if (mode === "plan") return;
    if (mode === "human-away") {
      if (!(await hasChanges(ctx.cwd))) return;
      const inspected = inspectAction({ toolName: "autogit-ship", input: { operation: "stage-commit-push" } }, ctx.cwd);
      const action = {
        ...inspected,
        summary: "autogit ship (stage, commit, and push current workspace changes)",
        category: "remote-mutation" as const,
        risk: "high" as const,
        route: "human" as const,
        reason: "Automatic push runs outside tool_call mediation and mutates a remote repository.",
        saferPath: "Review the worktree when Rajveer returns, then run autogit ship manually.",
        requiresHumanInYolo: false,
      };
      try {
        const record = recordDecision(action, {
          decision: "defer",
          reason: action.reason,
          saferPath: action.saferPath,
          reviewer: "policy",
        }, "pending", false);
        patchCockpit({
          phase: "REVIEW",
          approval: {
            id: record.id,
            agent: "Neura",
            task: record.category,
            exactAction: record.summary,
            boundary: record.verdict.reason,
            fallback: record.verdict.saferPath,
            risk: record.risk,
            approvable: false,
          },
        });
      } catch (error) {
        patchCockpit({ phase: "DEGRADED", degraded: "Autogit approval audit failed; push remains locked." });
        try { ctx.ui.notify(`autogit held; approval audit failed: ${error}`, "error"); } catch {}
      }
      return;
    }
    const p = run(["ship", "--id", id], ctx.cwd, { stdio: ["ignore", "ignore", "pipe"] });
    p.on("spawn", () => patchCockpit({ phase: "WORK", operation: { verb: "autogit", target: "stage · commit · push", startedAt: Date.now() } }));
    let err = "";
    p.stderr.on("data", (d) => { err += d; });
    const notify = (msg) => { try { ctx.ui.notify(msg, "error"); } catch {} }; // ctx may be stale after session end
    p.on("close", (code) => {
      // cmd /c exits 1 with "not recognized" when autogit is not installed — notify once, then mute
      if (code !== 0) {
        patchCockpit({ phase: "DEGRADED", operation: undefined, degraded: "Autogit ship failed." });
        addCockpitNotice({ id: "autogit", message: "Autogit ship failed", detail: err.trim() || "Inspect autogit output.", tone: "error", persistent: true });
        if (/not recognized|is not recognized/i.test(err)) {
          if (!missing) notify("autogit unavailable · automatic commit is off for this session");
          missing = true;
        } else {
          notify("autogit: " + (err.trim() || "ship failed"));
        }
      } else {
        patchCockpit({ phase: "COMPLETE", operation: undefined, degraded: undefined });
        removeCockpitNotice("autogit");
      }
    });
    p.on("error", () => {
      missing = true;
      patchCockpit({ phase: "DEGRADED", operation: undefined, degraded: "Autogit could not start." });
      addCockpitNotice({ id: "autogit", message: "Autogit unavailable", detail: "Automatic shipping is off for this session.", tone: "warning", persistent: true });
    });
  });
}
