import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { isolate } from './isolation.mjs';
const scratchRoot = isolate();
const repoRoot = path.resolve(import.meta.dirname, '../..');
const { parseRuntimeContract } = await import('../../agent/extensions/harness-health.ts');
const files = fs.readdirSync(path.join(repoRoot, 'agent/extensions'));
assert.equal(files.some((file) => file === "autogit.ts"), false, "retired autogit extension still loads");
const installerSource = fs.readFileSync(path.join(repoRoot, "install.ps1"), "utf-8");
const runtimeContract = JSON.parse(fs.readFileSync(path.join(repoRoot, "agent", "neura", "runtime-contract.json"), "utf-8"));
const packageManifest = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf-8"));
assert.match(installerSource, /\$retiredExtensions\s*=\s*@\("autogit\.ts"\)/, "installer does not retire the old autogit hook");
assert.match(installerSource, /Remove-Item -LiteralPath \$retiredPath -Force/, "installer does not remove the retired autogit hook");
assert.match(installerSource, /is retired but remains installed/, "drift check does not detect the retired autogit hook");
assert.match(installerSource, /function Get-PackageIdentity/, "installer cannot reconcile exact runtime package pins");
assert.match(installerSource, /runtime package is not exactly pinned/, "drift check ignores runtime package pins");
assert.match(installerSource, /runtime-contract\.json/, "installer does not consume the runtime contract");
assert.match(installerSource, /\$requiredPiVersion\s*=\s*\[string\]\$runtimeContract\.piVersion/, "installer does not enforce the runtime contract Pi version");
assert.match(installerSource, /\$schemaIsInteger\s*=\s*\(\$runtimeContract\.schemaVersion -is \[int\]\) -or \(\$runtimeContract\.schemaVersion -is \[long\]\)/, "installer allows a coercible non-integer runtime contract schema");
assert.equal(runtimeContract.schemaVersion, 1, "runtime contract schema version changed without migration");
assert.equal(runtimeContract.piVersion, packageManifest.devDependencies["@earendil-works/pi-coding-agent"], "runtime contract and development Pi pin disagree");
assert.equal(parseRuntimeContract(runtimeContract), runtimeContract.piVersion, "valid runtime contract was rejected");
assert.equal(parseRuntimeContract({ schemaVersion: "1", piVersion: runtimeContract.piVersion }), null, "string runtime contract schema was coerced");

console.log('PASS installer contract');

const functions = spawnSync(process.platform === 'win32' ? 'powershell' : 'pwsh', ['-NoProfile','-File',path.join(import.meta.dirname,'installer-functions.ps1'),'-Source',path.join(repoRoot,'install.ps1'),'-Scratch',scratchRoot], {env:process.env,encoding:'utf8',windowsHide:true,timeout:15000});
assert.equal(functions.status,0, 'Installer function verification failed: '+functions.stderr);
console.log(functions.stdout.trim());
