import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const sha = file => createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'neura-install-test-'));
const home = path.join(tmp, 'home');
const source = path.join(tmp, 'source');
const helper = path.join(source, 'agent/neura/runtime-install.mjs');
const live = name => name.startsWith('launcher/') ? path.join(home, '.local/bin/neura.cmd') : path.join(home, '.pi/agent', name.slice(6));
const stage = path.join(home, '.pi/neura-install-pending/stage');
const write = (file, data) => { fs.mkdirSync(path.dirname(file), {recursive: true}); fs.writeFileSync(file, data); };
const run = (mode, ok = true, env = {}) => {
  const result = spawnSync(process.execPath, [helper, ...mode.split(' ')], { encoding: 'utf8', env: {...process.env, HOME: home, USERPROFILE: home, PI_CODING_AGENT_DIR: path.join(home, '.pi/agent'), ...env} });
  assert.equal(result.status === 0, ok, `${mode}: ${result.stderr}`);
  return result;
};
const build = (extension = 'one.ts') => {
  write(path.join(source, 'agent/extensions', extension), extension);
  write(path.join(source, 'agent/neura/runtime-install.mjs'), fs.readFileSync(new URL('../..//agent/neura/runtime-install.mjs', import.meta.url)));
  write(path.join(source, 'agent/mcp.json'), '{}');
  write(path.join(source, 'launcher/neura.cmd'), '@echo off');
  const skillFiles = ['skills-registry.mjs', 'skills-manifest.json', 'skills/neura-verification/1.0.0/SKILL.md'];
  for (const name of skillFiles) write(path.join(source, 'agent/neura', name), fs.readFileSync(new URL(`../../agent/neura/${name}`, import.meta.url)));
  const names = [`agent/extensions/${extension}`, 'agent/neura/runtime-install.mjs', 'agent/mcp.json', 'launcher/neura.cmd', ...skillFiles.map(name => `agent/neura/${name}`)];
  const files = Object.fromEntries(names.map(name => [name, sha(path.join(source, name))]));
  write(path.join(source, 'agent/neura/release-manifest.json'), JSON.stringify({schemaVersion:1, neuraVersion:'2.5.1', piVersion:'1.0.4',nodeMinimum:'24.15.0',automaticExecutables:{git:{}}, runtimePackages:[],capabilities:{work:'default'},files}));
};
const seal = () => { run('prepare'); write(path.join(stage, 'agent/neura/.learn-runtime-lock'), 'receipt'); write(path.join(stage, 'agent/neura/node_modules/example.js'), 'pinned'); run('seal'); };
try {
  build();
  write(path.join(source, 'agent/extensions/one.ts'), 'changed source');
  run('prepare', false); // source bytes must match the release manifest
  write(path.join(source, 'agent/extensions/one.ts'), 'one.ts');
  const selection = path.join(home, '.pi/neura-skills.json');
  write(selection, JSON.stringify({schemaVersion: 1, enabled: ['neura-verification', 'neura-verification']}));
  assert.match(run('prepare', false).stderr, /invalid opt-in selection/);
  assert.equal(fs.existsSync(path.join(home, '.pi/neura-install-pending')), false, 'invalid selection reached staging');
  write(selection, JSON.stringify({schemaVersion: 1, enabled: ['neura-verification']}));
  const skillManifestFile = path.join(source, 'agent/neura/skills-manifest.json');
  const releaseFile = path.join(source, 'agent/neura/release-manifest.json');
  const skillManifestBytes = fs.readFileSync(skillManifestFile);
  const releaseBytes = fs.readFileSync(releaseFile);
  const badSkills = JSON.parse(skillManifestBytes);
  badSkills.skills[0].permissions.execute = true;
  write(skillManifestFile, JSON.stringify(badSkills));
  const badRelease = JSON.parse(releaseBytes);
  badRelease.files['agent/neura/skills-manifest.json'] = sha(skillManifestFile);
  write(releaseFile, JSON.stringify(badRelease));
  assert.match(run('prepare', false).stderr, /permissions are restrictions/);
  write(skillManifestFile, skillManifestBytes);
  delete badRelease.files['agent/neura/skills/neura-verification/1.0.0/SKILL.md'];
  badRelease.files['agent/neura/skills-manifest.json'] = sha(skillManifestFile);
  write(releaseFile, JSON.stringify(badRelease));
  assert.match(run('prepare', false).stderr, /not release-owned/);
  write(releaseFile, releaseBytes);
  assert.match(run('prepare', false, {NEURA_INSTALL_TEST_FAIL_PREPARE_AFTER:'1'}).stderr, /injected staging failure/);
  assert.equal(fs.existsSync(path.join(home, '.pi/neura-install-pending')), false, 'failed preparation left a shared transaction behind');
  const legacyModule = live('agent/neura/node_modules/user-package.js');
  write(legacyModule, 'unreceipted');
  assert.match(run('prepare', false).stderr, /unreceipted Learn runtime/);
  assert.equal(fs.readFileSync(legacyModule, 'utf8'), 'unreceipted');
  fs.rmSync(path.dirname(legacyModule), {recursive:true, force:true});
  write(live('agent/settings.json'), '{"credential":"synthetic-only"}');
  seal();
  run('activate', false, {NEURA_INSTALL_TEST_CRASH_DURING_COPY:'1'});
  const partial = `${live('agent/extensions/one.ts')}.neura-install-0.tmp`;
  assert.equal(fs.readFileSync(partial, 'utf8'), 'partial');
  write(selection, JSON.stringify({schemaVersion: 1, enabled: ['unsupported']}));
  run('recover'); // external opt-in corruption must not obstruct package rollback
  write(selection, JSON.stringify({schemaVersion: 1, enabled: ['neura-verification']}));
  assert.equal(fs.existsSync(partial), false, 'interrupted copy left a partial executable file');
  assert.equal(fs.existsSync(live('agent/extensions/one.ts')), false, 'partial copy reached live target');
  seal();
  const freshReceipt = JSON.parse(fs.readFileSync(path.join(stage, 'agent/neura/.install-state.json'), 'utf8'));
  run('activate', false, {NEURA_INSTALL_TEST_CRASH_AFTER: String(Object.keys(freshReceipt.files).length + 1)});
  const receiptIndex = Object.keys(freshReceipt.files).length;
  const absentMarker = path.join(home, '.pi/neura-install-pending/backup', `absent-${receiptIndex}`);
  fs.rmSync(absentMarker);
  run('recover', false);
  assert.equal(fs.existsSync(live('agent/neura/.install-state.json')), true, 'missing inventory marker changed live state');
  write(absentMarker, '');
  run('recover');
  assert.equal(fs.existsSync(live('agent/neura/.install-state.json')), false, 'interrupted first install left a release receipt');
  assert.equal(fs.existsSync(path.join(home, '.pi/neura-install-pending')), false, 'interrupted first install left a journal');
  seal(); run('activate'); run('check');
  const alternateAgent = path.join(tmp, 'alternate-agent');
  fs.cpSync(path.join(home, '.pi/agent'), alternateAgent, {recursive: true});
  run('check', true, {PI_CODING_AGENT_DIR: alternateAgent});
  write(path.join(alternateAgent, 'extensions/one.ts'), 'tampered');
  run('check', false, {PI_CODING_AGENT_DIR: alternateAgent});
  assert.equal(fs.readFileSync(live('agent/settings.json'), 'utf8'), '{"credential":"synthetic-only"}');
  const liveModule = live('agent/neura/node_modules/example.js');
  write(liveModule, 'user-edited');
  run('check', false);
  run('check --quick'); // Health checks only managed files; launch still verifies Learn bytes.
  seal(); run('activate', false);
  run('recover');
  write(liveModule, 'pinned');
  run('prepare');
  write(path.join(stage, 'agent/neura/.learn-runtime-lock'), 'receipt');
  write(path.join(stage, 'agent/neura/node_modules/new.js'), 'pinned');
  run('seal');
  write(liveModule, 'edited stale module');
  run('activate', false);
  assert.equal(fs.readFileSync(liveModule, 'utf8'), 'edited stale module');
  run('recover');
  write(liveModule, 'pinned');
  const retiredExtension = live('agent/extensions/autogit.ts');
  write(retiredExtension, 'user-owned');
  run('check', false); run('prepare', false);
  assert.equal(fs.readFileSync(retiredExtension, 'utf8'), 'user-owned');
  fs.rmSync(retiredExtension);
  const unexpectedModule = live('agent/neura/node_modules/unknown.js');
  write(unexpectedModule, 'unexpected');
  assert.match(run('check', false).stderr, /unknown Learn runtime file: agent\/neura\/node_modules\/unknown\.js/);
  fs.rmSync(unexpectedModule);
  // Upgrade removes only a previously owned stale extension.
  fs.rmSync(path.join(source, 'agent/extensions/one.ts'));
  build('two.ts'); seal(); run('activate'); run('check');
  assert.equal(fs.existsSync(live('agent/extensions/one.ts')), false);
  // Unknown extensions cannot load silently; an explicit user-owned hash allowlist preserves them.
  write(live('agent/extensions/custom.ts'), 'user code');
  run('check', false); run('prepare', false);
  write(path.join(home, '.pi/neura-user-extensions.json'), JSON.stringify({schemaVersion:1, extensions:{'custom.ts':sha(live('agent/extensions/custom.ts'))}}));
  run('check');
  write(live('agent/extensions/custom.ts'), 'changed'); run('check', false);
  write(live('agent/extensions/custom.ts'), 'user code');
  write(live('agent/mcp.json'), '{"user":"owned"}');
  run('prepare', false); // refuse to overwrite edited live configuration
  write(live('agent/mcp.json'), '{}');
  // Tamper detection checks bytes, not normalized text or a lockfile-only receipt.
  write(live('agent/extensions/two.ts'), 'tampered'); run('check', false); run('check --quick', false);
  write(live('agent/extensions/two.ts'), 'two.ts');
  seal(); run('activate', false, {NEURA_INSTALL_TEST_FAIL_AFTER:'2'});
  assert.equal(fs.readFileSync(live('agent/extensions/two.ts'), 'utf8'), 'two.ts', 'failed activation did not roll back');
  assert.equal(fs.readFileSync(live('agent/settings.json'), 'utf8'), '{"credential":"synthetic-only"}');
  run('check');
  // A forged previous receipt cannot claim a private file as a stale managed file.
  const receiptPath = live('agent/neura/.install-state.json');
  const originalReceipt = fs.readFileSync(receiptPath, 'utf8');
  const forgedReceipt = JSON.parse(originalReceipt);
  forgedReceipt.files['agent/neura/MEMORY.md'] = sha(live('agent/extensions/two.ts'));
  write(receiptPath, JSON.stringify(forgedReceipt));
  run('prepare', false);
  write(receiptPath, originalReceipt);
  // Abrupt process death leaves an actual stage, backups and journal to recover.
  const pending = path.join(home, '.pi/neura-install-pending');
  seal(); run('activate', false, {NEURA_INSTALL_TEST_CRASH_AFTER:'2'});
  run('check', false); run('prepare', false);
  run('recover', false, {NEURA_INSTALL_TEST_CRASH_DURING_RECOVER:'1'});
  const recoveryTemp = `${live('agent/extensions/two.ts')}.neura-recover-0.tmp`;
  assert.equal(fs.readFileSync(recoveryTemp, 'utf8'), 'partial');
  run('recover');
  assert.equal(fs.existsSync(recoveryTemp), false, 'interrupted rollback left a partial executable file');
  assert.equal(fs.readFileSync(live('agent/extensions/two.ts'), 'utf8'), 'two.ts');
  run('check');
  // Recovery must refuse an allowed-namespace private path, not only traversal.
  write(live('agent/neura/MEMORY.md'), 'private');
  seal();
  write(path.join(pending, 'journal.json'), JSON.stringify(['agent/neura/MEMORY.md']));
  run('recover', false);
  assert.equal(fs.readFileSync(live('agent/neura/MEMORY.md'), 'utf8'), 'private');
  fs.rmSync(pending, {recursive:true, force:true});
  // Reviewed updates must use a new immutable package version, not just a new hash.
  const packageName = 'agent/neura/skills/neura-verification/1.0.0/SKILL.md';
  const updateManifest = JSON.parse(fs.readFileSync(skillManifestFile));
  const updateRelease = JSON.parse(fs.readFileSync(releaseFile));
  fs.appendFileSync(path.join(source, packageName), '\nKeep evidence explicit.\n');
  updateManifest.skills[0].sha256 = sha(path.join(source, packageName));
  write(skillManifestFile, JSON.stringify(updateManifest));
  updateRelease.files[packageName] = updateManifest.skills[0].sha256;
  updateRelease.files['agent/neura/skills-manifest.json'] = sha(skillManifestFile);
  write(releaseFile, JSON.stringify(updateRelease));
  assert.match(run('prepare', false).stderr, /immutable skill version cannot be reused/);
  const updatedName = packageName.replace('1.0.0', '1.0.1');
  write(path.join(source, updatedName), fs.readFileSync(path.join(source, packageName)));
  fs.rmSync(path.join(source, packageName));
  updateManifest.skills[0].version = '1.0.1';
  updateManifest.skills[0].path = updatedName.slice('agent/neura/'.length);
  updateManifest.skills[0].source.path = updatedName;
  updateManifest.skills[0].source.version = '1.0.1';
  write(skillManifestFile, JSON.stringify(updateManifest));
  delete updateRelease.files[packageName];
  updateRelease.files[updatedName] = updateManifest.skills[0].sha256;
  updateRelease.files['agent/neura/skills-manifest.json'] = sha(skillManifestFile);
  write(releaseFile, JSON.stringify(updateRelease));
  seal(); run('activate'); run('check');
  assert.equal(fs.existsSync(live(packageName)), false, 'owned retired version was not removed');
  assert.equal(fs.existsSync(live(updatedName)), true, 'new immutable version was not installed');
  assert.equal(fs.readFileSync(live('agent/neura/MEMORY.md'), 'utf8'), 'private');
  console.log('PASS synthetic managed release install, upgrade, ownership, drift, rollback, interruption, immutable skill updates');
} finally { fs.rmSync(tmp, {recursive:true, force:true}); }
