import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { isolate } from './isolation.mjs';
const scratch = isolate();
const {bubblewrapArguments,assertWorkspaceHasNoLinks,validateProofRuntimeInventory} = await import('../../agent/neura/human-away-sandbox.ts');
const args=bubblewrapArguments('/workspace-fixture','printf synthetic');
for(const flag of ['--unshare-all','--clearenv','--die-with-parent','--new-session']) assert.ok(args.includes(flag));
assert.deepEqual(args.slice(-3),['sh','-lc','printf synthetic']);
assert.equal(args.includes('/mnt/c'),false);
assert.equal(args.includes(process.env.USERPROFILE),false);
const trust={uvVersion:'0.12.11',uvSha256:'a'.repeat(64),uvxSha256:'b'.repeat(64),wheels:{'proof.whl':'c'.repeat(64)}};
const inventory=['/trusted/uv/uv','/trusted/uv/uvx','/trusted/wheels',trust.uvSha256,trust.uvxSha256,`proof.whl\t${'c'.repeat(64)}`,'1'].join('\n');
assert.ok(validateProofRuntimeInventory(inventory,'/trusted/uv','/trusted/wheels',trust));
assert.equal(validateProofRuntimeInventory(inventory.replace('c'.repeat(64),'d'.repeat(64)),'/trusted/uv','/trusted/wheels',trust),null,'tampered proof wheel accepted');
const proofArgs=bubblewrapArguments('/workspace-fixture','uvx --version',validateProofRuntimeInventory(inventory,'/trusted/uv','/trusted/wheels',trust));
assert.ok(proofArgs.includes('/tmp/proof-wheels') && proofArgs.includes('/tmp/neura-bin/uvx'),'proof dependencies were not mounted read-only');
assert.match(proofArgs.at(-1),/sha256sum -c -[^]*UV_CACHE_DIR=\/tmp\/uv-cache/,'proof skipped in-sandbox integrity or fresh cache');
fs.mkdirSync(path.join(scratch,'inside'));
fs.mkdirSync(path.join(scratch,'outside'));
assert.doesNotThrow(()=>assertWorkspaceHasNoLinks(path.join(scratch,'inside')));
fs.symlinkSync(path.join(scratch,'outside'),path.join(scratch,'inside/link'),'junction');
assert.throws(()=>assertWorkspaceHasNoLinks(path.join(scratch,'inside')),/refused linked workspace entry/);
console.log('PASS sandbox contract; live WSL replay: npm run verify:sandbox');
